### ISSUE TITLE
Using .succint with a js matchMedia

### ISSUE THREAD

**Issue by Design2Well** [micjamking/succinct#14]
Nice plugin!

Playing around with .succinct today - calling it from a javascript media query. As the query sets a smaller .succinct size the textDefault truncates nicely. If the query tries to set a larger .succinct size it appears as if the textDefault is no longer based on the original but rather on the current. As a result, the only way to view a larger truncated length is to refresh the browser. 

Seems like you figured this out with the live demo input button. It would be great to have a reset we can call into the .succint plugin that works similarly. 

Haven't quite figured that out yet though.

**Comment by micjamking** [comment]
Hey @Design2Well, first off, thank you for using Succinct! 

I'm not sure if I understand you 100% correctly, but I'll try my best to help. If you can share some of the code describing your particular scenario that could help us figure out a proper solution. 

While I think you bring up a valid use case, my desire for succinct, at it's core, to be simple and driven by a singular purpose. I like to think of succinct more of as a helper module being included in your app, rather than a general purpose library.

The demo I created is in the development branch of this repo if you want to see how I put it together. It's fairly simple; I cache the text of the paragraph in a variable, call succinct on the original element object, and reset using the variable under certain conditions. For example, using matchMedia as a condition:

```js
// Cache the text of the target element
var ogText = $('.my-paragraph').html();
// Create variable of media query
var mq = window.matchMedia("(min-width:768px)");

// if above 768px...
if (mq.matches) {
  // ...display original (cached) text
  $('.my-paragraph').html(ogText);
}
// ...else if it's below 768px
else {
  // ...truncate text using succinct
  $('.my-paragraph').succinct();
}
```

If you have multiple conditions (ie, `if...else if...else if...` or `switch`) or nested conditions, you can reset the text to its original state (ie, `$('.my-paragraph').html(ogText)`) before each time you truncate, ensuring that the text is always being truncated based on its original value.

Hope this makes sense and let me know how everything goes :v:

**Comment by Design2Well** [comment]
Mike,

 

Thanks so much for responding so quickly. I basically got to this exact solution last night. Sometimes you just need to take a break. Again - super valuable little plug-in. Here was my code – in case anyone else is interested…

 

// Cache the text of the target element

var ogText = $('.work-description').html();

// Create variable of media query

var mq = window.matchMedia("");

// Create variable for timeout duration

var resizeTimeout;

 

function descLength(descL) {

              $(function(){

                             $('.work-description').succinct({

                                           ignore: false,

                                           size: descL

                             });

              });

              

              console.log(descL);

}

 

function onWidthChange(mq) {

              if (window.matchMedia("(min-width: 1020px)").matches) {

                             // window width at least 1020px

                             mq = "(min-width: 1020px)";

                             descLength(100);            

 

              } else if (window.matchMedia("(min-width: 660px)").matches) {

                             // window width at least 6600px

                             mq = "(min-width: 660px)";

                             descLength(40);

 

              } else if (window.matchMedia("(min-width: 480px)").matches) {

                             // window width at least 480px

                             mq = "(min-width: 480px)";

                             descLength(140);            

 

              } else {

                             // window width is less than 480px

                             descLength(50);              

              }

}

 

if (window.matchMedia) {

              // listen for dimension changes

              mq.addListener(onWidthChange);

              

              // as soon as the window loads, check width

              onWidthChange(mq);

}

 

window.onresize = function() {

              clearTimeout(resizeTimeout);

              // handle normal resize

              

              resizeTimeout = setTimeout(function() {

                             $('.work-description').html(ogText);

                             onWidthChange(mq);

                             

              }, 250); //set for 250ms delay

};

**Comment by micjamking** [comment]
Also, one other possible solution is to create a function that does the resetting and applies the correct value to succinct each time:

```js

function truncateText(element, size){
   var text = $('.my-paragraph').html();
}
```
