### ISSUE TITLE
Results in an empty string when the text has no space in them.

### ISSUE THREAD

**Issue by nagarajankannan** [micjamking/succinct#15]
This might be intentional but providing an option to truncate for the special cases like a string with no spaces be of much useful

**Comment by micjamking** [comment]
@nagarajankannan It is intentional; this was mentioned in issue #5, but strings without spaces can be truncated using simple CSS, so adding this functionality to a jQuery plugin seemed uneccessary. See here for example: http://codepen.io/micjamking/pen/1b32b6b6a43a1570a22eba7d03cd0619

Does your use case involve a situation where CSS would not work?

**Comment by nagarajankannan** [comment]
@micjamking I missed it as you said my use case can be solved with simple css thanks for the information.

**Comment by micjamking** [comment]
No problems. glad you got everything resolved.
